/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import modelo.Futbolista;

/**
 *
 * @author CRISTIAN
 */
public class adicionar extends javax.swing.JFrame {

    /**
     * Creates new form adicionar
     */
    public adicionar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        casacaTxt = new javax.swing.JTextField();
        ciTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        fechaTxt = new javax.swing.JTextField();
        posicionTxt = new javax.swing.JTextField();
        titulosTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel1.setText("NRO CASACA: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 20));

        jLabel2.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRAR FUTBOLISTA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 300, 40));

        jLabel3.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel3.setText("CI:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 30, 20));

        jLabel4.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel4.setText("NOMBRE: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, 30));

        jLabel5.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel5.setText("APELLIDO: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 20));

        jLabel6.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel6.setText("FECHA DE NACIMIENTO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, 20));

        jLabel7.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel7.setText("POSICION: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 20));

        jLabel8.setFont(new java.awt.Font("IBM Plex Sans", 1, 14)); // NOI18N
        jLabel8.setText("TITULOS GANADOS: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 20));
        jPanel1.add(casacaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 190, -1));
        jPanel1.add(ciTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 190, -1));
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, -1));
        jPanel1.add(apellidoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 190, -1));
        jPanel1.add(fechaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, -1));
        jPanel1.add(posicionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, -1));
        jPanel1.add(titulosTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, -1));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 380, 30));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton2.setText("VER LISTA ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 130, 30));

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("<-VOLVER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reg.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nom="CristianM_futbolistas.dat";
        try{
            ObjectOutputStream archivo=null;
            if(new File(nom).exists()){ //si existe adiciona
                archivo=new AddObjectOutputStream(new FileOutputStream(nom,true));
            }else{
                archivo=new AddObjectOutputStream(new FileOutputStream(nom,true));
            }
            Futbolista futbolista=new Futbolista();
            //recuperando datos
            boolean verify=true;
            int ci=0;
            try{
                ci=Integer.parseInt(this.ciTxt.getText());
                futbolista.setCi(ci);
            }catch(Exception e){
                verify=false;
                JOptionPane.showMessageDialog(null, "CI DEBE SER UN DATO NUMERICO");
            }
            int titulos=0;
            try{
                titulos=Integer.parseInt(this.titulosTxt.getText());
                futbolista.setTitulos_ganados(titulos);
            }catch(Exception e){
                verify=false;
                JOptionPane.showMessageDialog(null, "TITULOS GANADOS DEBE SER UN DATO NUMERICO");
            }
            int nro=0;
            try{
                nro=Integer.parseInt(this.casacaTxt.getText());
                futbolista.setNro_casaca(nro);
            }catch(Exception e){
                verify=false;
                JOptionPane.showMessageDialog(null, "CI DEBE SER UN DATO NUMERICO");
            }
            futbolista.setNombre(nombreTxt.getText());
            futbolista.setApellido(apellidoTxt.getText());
            futbolista.setFecha_nac(fechaTxt.getText());
            futbolista.setPosicion(posicionTxt.getText());
            if(nombreTxt.getText().equalsIgnoreCase("")||apellidoTxt.getText().equalsIgnoreCase("")||fechaTxt.getText().equalsIgnoreCase("")||posicionTxt.getText().equalsIgnoreCase("")){
                verify=false;
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
            }
            if(verify==true){
                JOptionPane.showMessageDialog(null, "FUTBOLISTA REGISTRADO CON EXITO!");
                archivo.writeObject(futbolista);
            }
            //guardando datos
            
            archivo.close();
        }catch(Exception e){
        }finally{
            //archivo.close();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listaYacciones adi=new listaYacciones();
        adi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menu men=new menu();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JTextField casacaTxt;
    private javax.swing.JTextField ciTxt;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField posicionTxt;
    private javax.swing.JTextField titulosTxt;
    // End of variables declaration//GEN-END:variables
}
