/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Futbolista;

/**
 *
 * @author CRISTIAN
 */
public class listaYacciones extends javax.swing.JFrame {

    /**
     * Creates new form listaYacciones
     */
    DefaultTableModel tabla=new DefaultTableModel();
    public listaYacciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarTabla();
        
    }
    public void mostrarTabla(){
        tabla.setColumnCount(0);
        tabla.setRowCount(0);
        tabla.addColumn("CI");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDO");
        tabla.addColumn("FECHA NACIMIENTO");
        tabla.addColumn("POSICION");
        tabla.addColumn("TITULOS");
        tabla.addColumn("NRO CASACA");
        this.futbolistas.setModel(tabla);
        ObjectInputStream archivo=null;
        String nom="CristianM_futbolistas.dat";
        try {
            archivo=new ObjectInputStream(new FileInputStream(nom));
            while(true){
                Futbolista fut=new Futbolista();
                fut=(Futbolista)archivo.readObject();
                String v[]=new String[7];
                v[0]=fut.getCi()+"";
                v[1]=fut.getNombre();
                v[2]=fut.getApellido()+"";
                v[3]=fut.getFecha_nac()+"";
                v[4]=fut.getPosicion()+"";
                v[5]=fut.getTitulos_ganados()+"";
                v[6]=fut.getNro_casaca()+"";
                tabla.addRow(v);
                
            }
        } catch (Exception e) {
        }finally{
            try {
                archivo.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        futbolistas = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        casacaTxt = new javax.swing.JTextField();
        cambioPosicion = new javax.swing.JTextField();
        PosicionElminarTxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        futbolistas.setBackground(new java.awt.Color(51, 51, 51));
        futbolistas.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        futbolistas.setForeground(new java.awt.Color(255, 255, 255));
        futbolistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(futbolistas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 900, 580));

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("<-Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 170, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ELIMINAR FUTBOLISTAS ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LISTA ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        jLabel4.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("DE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        jLabel5.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FUTBOLISTAS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("DE POSICION X: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("FUTBOLISTA DE CASACA NRO: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("MOSTRAR DATOS DEL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 20));
        jPanel1.add(casacaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 170, 30));

        cambioPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioPosicionActionPerformed(evt);
            }
        });
        jPanel1.add(cambioPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, 30));

        PosicionElminarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosicionElminarTxtActionPerformed(evt);
            }
        });
        jPanel1.add(PosicionElminarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 30));

        jButton4.setBackground(new java.awt.Color(0, 255, 102));
        jButton4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("VOLVER A LISTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 160, 30));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton5.setText("ELIMINAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 153));
        jButton6.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton6.setText("MOSTRAR");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, 30));

        jButton7.setBackground(new java.awt.Color(204, 204, 0));
        jButton7.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jButton7.setText("MODIFICAR ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 170, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("MODIFICAR LA POSICION DE ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 0));
        jLabel10.setText("MAS JOVENES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("IBM Plex Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("LOS JUGADORES QUE SEAN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ChampList.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menu men=new menu();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mostrarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String nombreArchivo="CristianM_futbolistas.dat";
        boolean flag =false;
        ObjectInputStream archivo=null; // de lectura
        ObjectOutputStream archivoAuxiliar=null; // de escritura
        String posicion=PosicionElminarTxt.getText();
        
        try {
            archivo=new ObjectInputStream(new FileInputStream(nombreArchivo));
            archivoAuxiliar=new ObjectOutputStream(new FileOutputStream("copia.dat", true));
            while(true){
                Futbolista fut=(Futbolista) archivo.readObject();
                if(fut.getPosicion().equalsIgnoreCase(posicion)){
                    //eliminar ese futbolista
                }else{
                    archivoAuxiliar.writeObject(fut);
                    flag=true;
                }
            }
        } catch (Exception e) {
        }finally{
            try {
                archivo.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
            try {
                archivoAuxiliar.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
            if(flag!=true){
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO");
            }else{
                JOptionPane.showMessageDialog(null, "ELIMINADO/S");
            }
            File f1=new File(nombreArchivo);
            File f2=new File("copia.dat");
            f1.delete();
            f2.renameTo(f1);
            
            mostrarTabla();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

        public int menorEdad(){
        int menor=9999;
        ObjectInputStream archivo=null;
        String nom="CristianM_futbolistas.dat";
        try {
            archivo=new ObjectInputStream(new FileInputStream(nom));
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            while(true){
                Futbolista fut=(Futbolista) archivo.readObject();
                LocalDate fechaNac = LocalDate.parse(fut.getFecha_nac(), fmt);
                LocalDate ahora = LocalDate.now();
                Period periodo = Period.between(fechaNac, ahora);
                if(periodo.getYears()<menor){
                    menor=periodo.getYears();
                }
            }
        } catch (Exception e) {
        }finally{
            try {
                archivo.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
            return menor;
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tabla.setColumnCount(0);
        tabla.setRowCount(0);
        tabla.addColumn("CI");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDO");
        tabla.addColumn("FECHA NACIMIENTO");
        tabla.addColumn("POSICION");
        tabla.addColumn("TITULOS");
        tabla.addColumn("NRO CASACA");
        this.futbolistas.setModel(tabla);
        ObjectInputStream archivo=null;
        String nom="CristianM_futbolistas.dat";
        int casacanro=-1;
        boolean flag=false;
        try{
                casacanro=Integer.parseInt(this.casacaTxt.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "LA CASACA DEBE SER UN DATO NUMERICO");
                 mostrarTabla();
            }
        try {
            archivo=new ObjectInputStream(new FileInputStream(nom));
            while(true){
                Futbolista fut=new Futbolista();
                fut=(Futbolista)archivo.readObject();
                if(fut.getNro_casaca()==casacanro){
                    String v[]=new String[7];
                    v[0]=fut.getCi()+"";
                    v[1]=fut.getNombre();
                    v[2]=fut.getApellido()+"";
                    v[3]=fut.getFecha_nac()+"";
                    v[4]=fut.getPosicion()+"";
                    v[5]=fut.getTitulos_ganados()+"";
                    v[6]=fut.getNro_casaca()+"";
                    tabla.addRow(v);
                    flag=true;
                }
                
            }
        } catch (Exception e) {

        }finally{
            try {
                archivo.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
            if(flag!=true){
                JOptionPane.showMessageDialog(null, "NO HAY COINCIDENCIAS");
                mostrarTabla();
            }else{
                JOptionPane.showMessageDialog(null, "MOSTRANDO DATOS");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String nombreArchivo="CristianM_futbolistas.dat";
        boolean flag =false;
        ObjectInputStream archivo=null; // de lectura
        ObjectOutputStream archivoAuxiliar=null; // de escritura
        String posicion=cambioPosicion.getText();
        
        try {
            archivo=new ObjectInputStream(new FileInputStream(nombreArchivo));
            archivoAuxiliar=new ObjectOutputStream(new FileOutputStream("copia.dat", true));
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            int menor=menorEdad();
            while(true){
                Futbolista fut=(Futbolista) archivo.readObject();
                LocalDate fechaNac = LocalDate.parse(fut.getFecha_nac(), fmt);
                LocalDate ahora = LocalDate.now();
                Period periodo = Period.between(fechaNac, ahora);
                if(periodo.getYears()==menor){
                    fut.setPosicion(posicion);
                    archivoAuxiliar.writeObject(fut);
                    flag=true;
                }else{
                    archivoAuxiliar.writeObject(fut);
                }
            }
        } catch (Exception e) {
        }finally{
            try {
                archivo.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
            try {
                archivoAuxiliar.close();
            } catch (Exception ex) {
                Logger.getLogger(listaYacciones.class.getName()).log(Level.SEVERE,null,ex);
            }
            if(flag!=true){
                JOptionPane.showMessageDialog(null, "NO HAY MODIFICACIONES");
            }else{
                JOptionPane.showMessageDialog(null, "MODIFICADO/S");
            }
            File f1=new File(nombreArchivo);
            File f2=new File("copia.dat");
            f1.delete();
            f2.renameTo(f1);
            
            mostrarTabla();
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void cambioPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambioPosicionActionPerformed

    private void PosicionElminarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosicionElminarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosicionElminarTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaYacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaYacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaYacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaYacciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaYacciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PosicionElminarTxt;
    private javax.swing.JTextField cambioPosicion;
    private javax.swing.JTextField casacaTxt;
    private javax.swing.JTable futbolistas;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
